#
#  .swiftlint.yml
#  Nimli
#
#  Created by Haruto K. on 2025/03/21.
#

type_name:
  min_length: 4
  max_length: 60

identifier_name:
  min_length: 4
  max_length: 60

disabled_rules:
  - trailing_whitespace
  - file_length
